# Generated by Django 4.2.3 on 2023-11-25 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('direccion', models.TextField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pc', models.CharField(max_length=100)),
                ('descripcion_pc', models.TextField()),
                ('descripcion_problema', models.TextField()),
                ('prioridad', models.IntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')])),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('En proceso', 'En proceso'), ('Cerrado', 'Cerrado')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.cliente')),
            ],
        ),
    ]
