# Generated by Django 4.2.3 on 2023-11-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soporte',
            name='prioridad',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=20),
        ),
    ]
